### ISSUE TITLE
Yearly Contact with Producer - The Bold Roast

### ISSUE THREAD

**Issue by porteriffic** [creativedisturbance/podcasts#235]
Since there are 3 producers for this channel, have them decide their roles for the rest of the year and plan out the rest of the year for their channel. Also ask what their expectations are, gather their feedback, etc.

**Comment by coreysmart92** [comment]
I have emailed the producers, Stephanie and Anvit, about The Bold Roast: Student Conversations to setup a meeting. (9/14/15)

**Comment by amb141330** [comment]
I think since it's the start of the semester, it'll be a good time to re-contact all producers. I did so at the beginning of summer and some of them said they were expecting podcasts toward the end/in the fall. This will be a good time to touch base with them. 

Closing this issue and will open one for all producers.
