### ISSUE TITLE
Quality Test Forms - Lina

### ISSUE THREAD

**Issue by cassininazir** [creativedisturbance/podcasts#258]
We need your help to launch the new version of Producer Forms! Please take time to **complete these  before the Saturday, Aug. 29**  and **add your comments/suggestions to this GitHub issue**. 
1. Login to test server at http://production.cd2.texashats.org/login. Note that you may reset your password or register as a new user. 
2. Click the link to **Forms for producers and guests**. (Yes, this link needs to be improved!) 
3. Then do the following: 
   - Submit 1 of each of the 4 forms (new channel, guest, submit podcast, producer) 
   - Partially complete each of the four forms and "save" your content for later
   - Delete at least one of your saved forms

Remember, this form will be used by producers and guests. Help us identify pain points for them. A few thoughts to get you started: 
- How can we improve the completion page? 
- What tasks can be made easier? 
- What information might be missing from these forms? 
- What information does the podcast team need that should be included on these forms?

**Comment by linamoon** [comment]
<h2>Dashboard</h2>

![image](https://cloud.githubusercontent.com/assets/10729556/9556519/e9337684-4d9a-11e5-884a-a879b67ce90e.png)
- This looks like a social networking site profile dashboard. How can I upload my profile picture here?

![4099f49e-58ff-4846-b270-60cbad3ae249](https://cloud.githubusercontent.com/assets/10729556/9555042/2a3b9e3c-4d90-11e5-8a41-ff1adbf5ac57.png)
- If I'm coming to the website for the first time and see the Saved Forms section before the actual forms, I might get confused and think I have saved forms already - this could use an indicator that the user currently has no saved forms if there aren't any, and might even be moved below the New Forms section.
- There are no headings or copy of any kind with the stats next to the Saved Forms - at a glance, this makes me think that these are my stats, and not for CD as a whole.

<h2>Forms Overall</h2>
- There is no Cancel button to take me back to the home page if I find that I'm on the wrong form - if the user doesn't think to press the back button on their browser to go back, they are forced to save the form to go back and delete it from the home page.
- I can only delete my form from the Home page - I can't actually do it in the form.

**Form Save Completion Page**
![a77a3f1b-5148-4c5d-bba3-12498c6f31e1](https://cloud.githubusercontent.com/assets/10729556/9555438/b3d56b6c-4d92-11e5-87fa-51f5e0b12514.png)
- Icon could use a little work!
- Having the heading/title of the form I just saved (as well as the responses) would remind me what I just saved
- Would like to have an Edit button on the page - in case if the user realizes they need to go back and edit in that moment
- Would be nice to have the links to create other forms at the bottom of the page (as they are on the home page)

![e3e8ed65-43ab-4e4a-92b7-30cdbcd97de1](https://cloud.githubusercontent.com/assets/10729556/9555537/5079370a-4d93-11e5-946c-f76652e3fcab.png)
- Not sure why, but when I logged back in after a while the title of my channel had been shortened - a bug?
- Would be good to have a Last Edited date along with Creation Date.

**After Submitting the Form**
- Would be good to have a section called Submitted Forms next to Saved Forms.

**Deleting a Saved Form**
![image](https://cloud.githubusercontent.com/assets/10729556/9556447/64ccf85c-4d9a-11e5-8213-f4687aa7a907.png)
Change copy to:
- "Are you sure you want to delete this entry? You won't be able to get it back later."
- "Yes, I want to delete this form"
- "No, don't delete"

<h2>Channel Form</h2>

**Number of Podcasts**
![dd65b009-60f0-47fb-8ab5-c14fecf7560b](https://cloud.githubusercontent.com/assets/10729556/9555192/3addec62-4d91-11e5-850e-36447dc98816.png)
- Perhaps this should also ask how these podcasts will be spaced out (i.e. 2 podcasts a month, etc.)

**Uploading Images**
![d7406c78-8470-446d-b650-4378985fd086](https://cloud.githubusercontent.com/assets/10729556/9555226/631c1924-4d91-11e5-9607-b61829bdd91e.png)
- The form says images, but you're only able to upload one image - possible to upload multiple (say max of 3)?
- Would be very helpful for the album art designer if producers could write a short blurb about why they chose that image, and what meanings they would like the art to convey.

**Listing Sponsors**
![6793960d-aea4-440b-91c3-64314cd55b5b](https://cloud.githubusercontent.com/assets/10729556/9555280/9f1c9c32-4d91-11e5-91d5-51731c6930ab.png)
- Am I able to list multiple sponsors using commas? Is this acceptable?

**Comments**
![94ef43ac-f08f-462e-b135-3b25a70496c4](https://cloud.githubusercontent.com/assets/10729556/9555286/a80ea1aa-4d91-11e5-9361-5b95d7561623.png)
- Perhaps instead of the word Comments, Additional Instructions might clarify the task a little better.

**Comment by linamoon** [comment]
<h2>Guest Form</h2>

**Header**
![image](https://cloud.githubusercontent.com/assets/10729556/9555676/4020e76c-4d94-11e5-96b9-fa2c3a43aab3.png)
- I like the idea of having examples of Voices, or links to other Voices' podcasts, but a carousel might be a distracting implementation - might be better to have a short row of 4-5 podcast examples below introductory copy

**Photo Upload**
![image](https://cloud.githubusercontent.com/assets/10729556/9555743/ea582e70-4d94-11e5-9eb0-50cbdeff27b4.png)

![flower_avatar_0025](https://cloud.githubusercontent.com/assets/10729556/9555739/df588452-4d94-11e5-96ae-3b2b9c489b93.jpg)
- The instructions say not to upload photos smaller than 300x300, but I can ignore this. I can be this tiny flower. I can also upload giant wallpaper-size images.

**Legal Copy**
![screen shot 2015-08-28 at 2 58 21 pm](https://cloud.githubusercontent.com/assets/10729556/9555824/949a2c94-4d95-11e5-80cd-8944e9709dc2.png)
- This could be spaced out a little better.

**Saved Form**
![image](https://cloud.githubusercontent.com/assets/10729556/9555800/64171942-4d95-11e5-93a2-72e32293a7b2.png)
- Instead of having Guest's name as the title of the form, having something like "Form for Guest Lina Moon"

**Comment by linamoon** [comment]
<h2>Podcast Form</h2>

**Header**
![image](https://cloud.githubusercontent.com/assets/10729556/9555894/161378ac-4d96-11e5-9af2-3208969dd787.png)
- Having the process up here is great - perhaps we should do this for the other forms as well.

**Choosing a Channel**

![image](https://cloud.githubusercontent.com/assets/10729556/9556074/840d4e36-4d97-11e5-89d5-2c8220c93068.png)
- Should I also be filling out a New Channel Form if I choose this option? What if I had just submitted a New Channel Form?

![image](https://cloud.githubusercontent.com/assets/10729556/9555986/ca963620-4d96-11e5-8bee-7732a9ddd100.png)
- Perhaps the concept of Primary and Secondary channels could be explained better with some copy?

![image](https://cloud.githubusercontent.com/assets/10729556/9555976/b1ed7ef8-4d96-11e5-9b37-4eeb522ca3c7.png)
- Hello there

**Website**
![image](https://cloud.githubusercontent.com/assets/10729556/9556032/26c9f9c2-4d97-11e5-97ae-d51c42a85bb4.png)
- Whose website should this be?

**Number of Voices**
![image](https://cloud.githubusercontent.com/assets/10729556/9556087/b086ac5a-4d97-11e5-8399-01b076b25aef.png)
- Does this include the host or whomever is filling out the form as well, or only guests?

![image](https://cloud.githubusercontent.com/assets/10729556/9556132/0f103660-4d98-11e5-9652-d31d5c441cc3.png)
- This might be good to have in such a way that selecting 3 voices from the drop-down automatically creates the same number of Voice Details.
- The Delete icon needs to be larger
- Would be nice to have copy at the bottom that says something like "Don't forget to make sure that Voice names are spelled correctly - names are important to people!"

**Comment by linamoon** [comment]
<h2>Producer Form</h2>

**Header**
![image](https://cloud.githubusercontent.com/assets/10729556/9556351/a64fa17c-4d99-11e5-8bca-10822c4fe9d0.png)
- Should have some kind of actionable link/button back to producer's channel or podcasts

**Co-Producers**
![image](https://cloud.githubusercontent.com/assets/10729556/9556414/252fa73a-4d9a-11e5-86ad-100f7629e6ca.png)
- Should this have a drop-down to choose the number of co-producers, such as choosing the number of Voices in the Podcast form (above)?
