### ISSUE TITLE
Podcast forms for Pam Grant Ryan

### ISSUE THREAD

**Issue by amb141330** [creativedisturbance/podcasts#270]
Need the podcast forms for this podcast still. Can you fill this out as soon as possible? @rmalina

**Comment by rmalina** [comment]
today
roger

**Comment by rmalina** [comment]
ashton
sorry
i made a type 
it should be 1984 not 1986 in this text 

roger

Pamela Grant Ryan tells the story of her work as managing editor of the Leonardo Journal since 1986  CORRECT TO 1984 - including the rapid transformation into fully digital multimeda publications and the rapid growth of the Leonardo Journal that has accompanied the explosive growth of the international art-science-technology audience over the past 50 years. Her discussant is Roger Malina.

**Comment by amb141330** [comment]
@rmalina Did you mean to make the channel Pioneers and Pathbreakers? Wouldn't this be on the New Leonardos channel due to the guest speaker?

**Comment by coreysmart92** [comment]
I spoke with Roger and confirmed that it is to be published on the Pioneers and Pathbreakers channel. (9/1/15)

**Comment by rmalina** [comment]
It could go in either
Pioneers maybe better

roger malina

**Comment by coreysmart92** [comment]
I have scheduled it for Pioneers and Pathbreakers, but if you want I can set the secondary channel to New Leonardos. (9/1/15)

**Comment by rmalina** [comment]
Sure
Didn't know you could do that

roger malina

**Comment by coreysmart92** [comment]
No problem, it is done. (9/1/15)
