### ISSUE TITLE
Jack McKay - Missing Podcast Forms

### ISSUE THREAD

**Issue by coreysmart92** [creativedisturbance/podcasts#292]
@coreysmart92 @rmalina This issue is to keep tracking of Jack McKay's Bold Roast podcast form completion. Close this issue when forms are complete. (9/8/15)

**Comment by rmalina** [comment]
coorey
i have filed the form and it is ready to publish
i listened to your edited version and its great

roger

Dear Roger,
Sorry for sending this late, but here is the edited version of the Jack McKay Podcast. First it still needs forms to be published. Second it ended rather abruptly around 12 mins, I am not sure if that was where you planned to end it or not. I added one of your rap-ups from another podcast so that the podcast didn't just cut off. Please let me know if you would like anything else edited or changed, thank yo

dont close this until the podcast has been published
roger

**Comment by rmalina** [comment]
form filed
and send to guest to check and correct
wait for me to confirm the guest approves it
before you publish
roger

On Tue, Sep 8, 2015 at 2:35 PM, coreysmart92 notifications@github.com
wrote:

> @coreysmart92 https://github.com/coreysmart92 @rmalina
> https://github.com/rmalina This issue is to keep tracking of Jack
> McKay's Bold Roast podcast form completion. Close this issue when forms are
> complete. (9/8/15)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/creativedisturbance/podcasts/issues/292.

## 

Roger F Malina
is in Dallas
1-510-853-2007

**Comment by rmalina** [comment]
mckay has approved his form and podcast
you have authorisation to publish
roger

ey Roger,

Looks perfect, thanks for asking me to check.

Cheers,
Jack

---

From: leonardo.isast@gmail.com [leonardo.isast@gmail.com] on behalf of roger malina [rmalina@alum.mit.edu]
Sent: 20 September 2015 18:33
To: Jack McKay Fletcher
Subject: Fwd: CREATIVE DISTURBANCE - New Podcast Info Form

jack

**Comment by coreysmart92** [comment]
Closing: The forms are in and the podcast is published. (9/28/15)
