### ISSUE TITLE
ideas for art and climate change

### ISSUE THREAD

**Issue by yvantina** [creativedisturbance/podcasts#333]
@porteriffic @coreysmart92 check out the link !
https://www.artsy.net/article/artsy-editorial-nine-artists-respond-to-climate-change

**Comment by porteriffic** [comment]
@yvantina Thanks for sharing the link with us but please don't make "ideas" a GitHub issue since technically it's not an issue. This helps us keep our GitHub from piling up and looking clutter. Please send future ideas to this GitHub issue that I started for Art & Climate Change: [COP21 Art & Climate Change Prep](https://github.com/creativedisturbance/podcasts/issues/288)
