### ISSUE TITLE
Wordpress Secondary Channel

### ISSUE THREAD

**Issue by coreysmart92** [creativedisturbance/podcasts#364]
The secondary channel in wordpress podcast pages does not work. Can you fix this so that a podcast can be be published on two separate channels without making separate podcast pages. If possible include a function which designates one channel as the primary/main channel.

**Comment by dylanorgeron** [comment]
@coreysmart92, you want to be able to create a post in wordpress once and have it appear on two channels, with both channels listed on the podcast page?

**Comment by coreysmart92** [comment]
Preferably wordpress would just add the podcast to the other channel's page(podcast list). The secondary channel option in wordpress is currently just for show. I have been duplicating and altering any podcast that should go on two channels. I do not believe it is necessary to alter the podcast page just the channel pages. Does that answer your question?

**Comment by dylanorgeron** [comment]
I can make that change, so that any podcasts with a secondary channel will be shown on both channels' pages. However, any podcast posts you made twice will then be duplicated on the secondary channels. You'll need to go in and remove all of those podcasts to fix the duplication. The change is easy to implement, but I want to do it at a time when you're free to remove the duplicates immediately to prevent users from seeing any errors. Let me know when you'll be in the lab so I can come back and take care of this.

**Comment by dylanorgeron** [comment]
@amb141330 bringing you in on this one as well
