### ISSUE TITLE
a new tool to experiment ?

### ISSUE THREAD

**Issue by yvantina** [creativedisturbance/podcasts#365]
@cassininazir @rmalina Have you heard about this ? https://medium.com/@periscope/up-periscope-f0b0a4d2e486 Frank and I are going to experiment this in our classes for personal meetings ! just wanted to bring it to your attention since it almost works the same as blab.im  - not sure if relevant for podcasts 
yvan

**Comment by cassininazir** [comment]
Yes. Blab, Periscope and Meerkat are streaming video services that solve similar needs. Periscope is primarily for mobile users. Blab works well on desktop environment.

Sent from my iPhone

On Oct 19, 2015, at 4:07 PM, yvantina <notifications@github.com<mailto:notifications@github.com>> wrote:

@cassininazirhttps://github.com/cassininazir @rmalinahttps://github.com/rmalina Have you heard about this ? https://medium.com/@periscope/up-periscope-f0b0a4d2e486 Frank and I are going to experiment this in our classes for personal meetings ! just wanted to bring it to your attention since it almost works the same as blab.im - not sure if relevant for podcasts
yvan

**Comment by yvantina** [comment]
Okay - thanks !
