### ISSUE TITLE
prioritising

### ISSUE THREAD

**Issue by rmalina** [creativedisturbance/podcasts#607]
ashton
just checked the excelt scheduling sheet
there are a mot of pod casts by yvan and me
can you give these lower priority than
ones from non local producers
-women
other languages than english 
as we discussed
roger

**Comment by amb141330** [comment]
I did just make a few more changes, but I did leave some of it where it was due to two things:

We're moving to four podcasts a week and I want to make sure Corey and Hal have ample time to get the information they need for publications. Also, I want to keep channels with multiple podcasts (like Other Planes or the Turkish channel) publishing in different weeks rather than all at once to spread out there content.

**Comment by rmalina** [comment]
what happened to the roots of curiosity group?
when is there next portuguese podcast
roger

Roger F Malina
is in Paris 33(0)6-80-45-94-47
To: all family and Leonardo friends- we are having a party to celebrate the
50th
anniversary of the founding of Leonardo on Saturday June 18 in Paris from
15h-24h !- if you are in Paris then and can attend we would be delighted to
invite you. Contactme.

**Comment by amb141330** [comment]
I haven't heard from them. I sent them an email when I emailed all the producers. I'll send them another and ask what they have planned.
