### ISSUE TITLE
Stats page not updating

### ISSUE THREAD

**Issue by amb141330** [creativedisturbance/podcasts#630]
creativedisturbance.org/stats page has not been updated since April

can you give me an update on this?

**Comment by dylanorgeron** [comment]
![image](https://cloud.githubusercontent.com/assets/6401465/17155468/d5384f22-534a-11e6-9ed7-e9d85987b2f1.png)

**Comment by amb141330** [comment]
Do you want me to contact Brett and find out about this? Obviously if we've paid for it and haven't received service that's an issue.

**Comment by dylanorgeron** [comment]
Cassini has been on it for awhile. I think that with Arteca it has fallen to the side. It's not critical right now because there are other things that I can be doing with Skedge that don't require an upgrade. I plan on meeting with Cassini soon to discuss a few things, I'll see about moving control of the migration over to myself, as there are bound to be issues or questions they will ask about the server and our needs that I may have to answer.

**Comment by amb141330** [comment]
Alright, this is a duplicate issue as you've brought to my attention so I'll close this one.

**Comment by cassininazir** [comment]
HostGator has made the changes! May take a bit of time for hte changes to propagate. All the passwords and such will be the same.

![screen shot 2016-08-03 at 3 51 47 pm](https://cloud.githubusercontent.com/assets/1661430/17381574/37e3357c-5992-11e6-8a0e-8698a379af2b.png)
![screen shot 2016-08-03 at 3 52 09 pm](https://cloud.githubusercontent.com/assets/1661430/17381582/3f9ae904-5992-11e6-811d-7fd2d405fa57.png)

Our VPS is active but IP addresses have not yet propagated.

![screen shot 2016-08-03 at 3 53 06 pm](https://cloud.githubusercontent.com/assets/1661430/17381612/6aa76ad2-5992-11e6-8fef-43b7fbc6b297.png)
