### ISSUE TITLE
Error Establishing Database Connection

### ISSUE THREAD

**Issue by amb141330** [creativedisturbance/podcasts#656]
I've tried connecting to creativedisturbance.org both in my normal browser and in incognito. 

I keep getting a page saying "Error Establishing Database Connection"

Any idea what may be causing this?

**Comment by amb141330** [comment]
It's working now, but I'm not sure what causes this to begin with.

**Comment by cassininazir** [comment]
@colin-c was this related to install JVM earlier?

**Comment by cassininazir** [comment]
Confirmed, it is working now. @colin-c was installing server components earlier today which we knew had the possibility of knocking the server down for a short while. Will see if he confirms.

**Comment by magicspacekiwi** [comment]
@cassininazir I had to leave before I could install Solr, so that shouldn't be it actually.
This has happened before from PHP consuming so much memory that the system kills mysqld to prevent the server from crashing.

**Comment by magicspacekiwi** [comment]
@cassininazir I just tried to check the server logs to be sure, but it's not set up to log kernel events (like when the system is forced to kill processes due to resource starvation).

I just enabled kernel logging so we'll be able to confirm 100% next time.
Let me know if it happens again @amb141330

**Comment by magicspacekiwi** [comment]
CD has been migrated to a server with significantly more memory.
This won't be an issue anymore.
