### ISSUE TITLE
Unable to Upload Image in Wordpress - Creative Disturbance!

### ISSUE THREAD

**Issue by ganeshcreation** [creativedisturbance/podcasts#659]
I am unable to upload an image when adding details for a new person in creative disturbance - word press. I am getting a blank screen like this when trying to upload an image.

I tried it in multiple browsers and also in Incognito mode just to see if there is any issue with Cache , but the issue still exists. 

<img width="1278" alt="screen shot 2017-04-05 at 3 01 41 pm" src="https://cloud.githubusercontent.com/assets/25909611/24724650/8d63ac12-1a11-11e7-8f80-68c2fa209596.png">

**Comment by magicspacekiwi** [comment]
Appears to be due to some security options I had set.
I had set [X-Frame-Options](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options) to deny all. I've adjusted it to allow same-origin framing.

@ganeshcreation Should be fixed now, give it a go.

**Comment by cassininazir** [comment]
Ganesh can you confirm this works for you now?

Sent from my iPhone

On Apr 5, 2017, at 3:39 PM, Colin Campbell <notifications@github.com<mailto:notifications@github.com>> wrote:


Appears to be due to some security options I had set.
I had set X-Frame-Options<https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options> to deny all. I've adjusted it to allow same-origin framing.

@ganeshcreation<https://github.com/ganeshcreation> Should be fixed now, give it a go.

-

**Comment by ganeshcreation** [comment]
I'll check it and get back to you shortly!
Thanks!

Best,
Ganesh

Get Outlook for iOS<https://aka.ms/o0ukef>




On Wed, Apr 5, 2017 at 5:05 PM -0500, "Cassini Nazir" <notifications@github.com<mailto:notifications@github.com>> wrote:

Ganesh can you confirm this works for you now?

Sent from my iPhone

On Apr 5, 2017, at 3:39 PM, Colin Campbell <notifications@github.com<mailto:notifications@github.com>> wrote:


Appears to be due to some security options I had set.
I had set X-Frame-Options<https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options> to deny all. I've adjusted it to allow same-origin framing.

@ganeshcreation<https://github.com/ganeshcreation> Should be fixed now, give it a go.

-

**Comment by ganeshcreation** [comment]
It works fine now!
Thanks a lot!

Best,
Ganesh
________________________________
