### ISSUE TITLE
CD to ARTECA qualification sheet

### ISSUE THREAD

**Issue by ritwikjk** [creativedisturbance/podcasts#667]
Develop process sheet for moving podcasts from CD and republishing on Arteca. What qualifies the podcast to be published in arteca?  Try to develop metrics.

**Comment by yusrak** [comment]
Quality of sound
Minimum # of podcast
Subject aligns with the title of podcast/podcast relevant to content
Peer reviewed-listener
# of downloads/popularity
Language

**Comment by ritwikjk** [comment]
- Quality of Sound 
- Minimum Number of podcasts on a channel.
- Peer Review podcasts- listener feedback
- Number of downloads- popularity
- Language 
- Title of podcast relevant to content

**Comment by OskarOlssonCD** [comment]
@ritwikjk I would suggest that any multilingual podcast should be posted with a translation. This could be done with text.
Does Arteca include a transcript feature?

**Comment by OskarOlssonCD** [comment]
@ritwikjk @yusrak @rmalina   I think it might be worth it to explore a different storage solution specifically for ARTECA podcasts. Since these are the episodes that we present to MIT's audience, we could look at reducing the issues that MP3 files are known for, such as artifacts. FLAC / WAV are larger, but much higher  fidelity. They also cause less strain on the ears of the listener. Since a lot of our audience will most likely be listening through earbuds or lower-tier monitors, it might be worth it to consider the effects of long-term listening. 

Number of downloads might not be a clear enough metric to measure the popularity of podcasts. For example, any time I have listened to a CD podcast I have not necessarily downloaded it. It looks like LibSyn only measures downloads. Are we measuring clicks as a popularity metric? If not, is there a way that we can start? The Hubspot plugin for wordpress looks promising. 

One other option would be to introduce a feedback function to be used by viewers. This could be anonymously collected and not posted publicly. We could use this data to figure out which aspects of channels are resonating with listeners.

**Comment by cassininazir** [comment]
@OskarOlssonCD No transcript feature currently. What data would be in transcript? 

Regarding different file formats, this should be a both/and scenario: upload both .mp3 and a lossless audio format. We'll need a process to make this happen.

**Comment by OskarOlssonCD** [comment]
@cassininazir 
I have read that Google Docs is able to transcribe audio into text, but I haven't tried it yet. Of course, that would still leave the issue of translation.

**Comment by arfaye** [comment]
How is the text on the website translated when visitors select a language? I’m not a web developer so I don’t know but if it is automatic, will the system in place not automatically translate a transcription?

**Comment by arfaye** [comment]
@OskarOlssonCD I wasn't sure if you were notified of another response since I didn't actually @ you.

**Comment by arfaye** [comment]
@OskarOlssonCD you created a process sheet for moving podcasts correct? If so, I'm wondering if y'all are okay with using the new quality measurements sheet to qualify podcasts from CD to be moved to ARTECA in the first place or if we need a separate one.

**Comment by OskarOlssonCD** [comment]
@arfaye, I think that the same sheet can probably be used for the ARTECA podcasts. After all, we should be shooting for high overall quality on both CD and ARTECA. @ritwikjk I suggest we e-mail this qualification sheet to our producers along with an announcement about CD's involvement with ARTECA. If we haven't done that already, it will help give our producers a way to judge their own material and give them an incentive for producing high-quality content for CD. After all, having a STEAM podcast hosted by MIT for the next 50 years would look pretty good on just about any CV.

**Comment by arfaye** [comment]
Okay! I wanted to make sure that was the plan before I closed this issue.
